### PR TITLE
fix the buggggggggggg

### PR DESCRIPTION
**Pull request by sandaon**

### CODE REVIEW

**Comment by b00902130** [comment]
`add mail13`
`query -f"Liz"`
就沒跑出東西了

**Comment by sandaon** [comment]
but 我有欸

**Comment by sandaon** [comment]
add mail13
13
query -f"Liz"
13

**Comment by b00902130** [comment]
`add mail1`
`add mail10`
`add mail12`
`add mail13`
`query -f"Liz"`
試試

**Pull request merged**
